---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at <https://ds202-at-isu.github.io/labs.html> for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.

All submissions to the github repo will be automatically uploaded for grading once the due date is passed. Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

## 12.1

-   Harrison's Notes: Already done before class.
-   Madison's Notes: Done before class and installed Git.

## 12.2

-   Harrison's Notes: Repo created by github classroom.
-   Madison"s Notes: Repo and joined the github classroom.

## 12.3

-   Harrison's Notes: No issues, downloaded fine, git already setup.
-   Madison"s Notes: Issues with git not setting up, fixed by changing project location.

## 12.4

-   Harrison's Notes: Worked fine, no issues commiting locally.
-   Madison"s Notes: Worked Good, no issues.

## 12.5

-   Harrison's Notes: Needed to enter github username and token to push to remote repo, worked fine.
-   Madison's Notes: No issues, had to enter username and password.

## 12.6

-   Harrison's Notes: Changes propagated 
-   Madison's Notes: Confirmed changes.


